const Exercicios = {
    "18-25": {
        "Ganho de massa muscular": {
            "Magro": [
                {
                    "nome": "Supino",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 8-12",
                    "intervalo": "Descanso de 60-90 segundos",
                },
                {
                    "nome": "Barra Fixa",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 8-12",
                    "intervalo": "Descanso de 60-90 segundos",
                },
                {
                    "nome": "Agachamento Livre",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 90 segundos",
                },
                {
                    "nome": "Rosca Direta",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Desenvolvimento com Halteres",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Leg Press",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 90 segundos",
                },
                {
                    "nome": "Puxada Alta",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Stiff",
                    "musculosAlvo": ["Pernas", "Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Levantamento Terra",
                    "musculosAlvo": ["Costas", "Pernas", "Abdômen"],
                    "repeticoes": "3 sets de 8-12",
                    "intervalo": "Descanso de 60-90 segundos",
                },
                {
                    "nome": "Braço com Barra",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Crucifixo Inclinado",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
            "Padrão": [
                {
                    "nome": "Flexão de Braço",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Remada Curvada",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Afundo",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Braço Corda",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Elevação Lateral",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Cadeira Extensora",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Flexão Declinada",
                    "musculosAlvo": ["Peitoral", "Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Puxada na Máquina",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Agachamento Frontal",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
            "Acima do Peso": [
                {
                    "nome": "Flexão de Braço Inclinada",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Pulldown",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Agachamento com Barra",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Braço Testa",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Desenvolvimento Arnold",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Flexora",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Pull-Up com Peso Adicionado",
                    "musculosAlvo": ["Costas", "Braço"],
                    "repeticoes": "3 sets de 8-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Caminhada com Peso",
                    "musculosAlvo": ["Perna", "Abdômen"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Rosca Martelo",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
        },
        "Perder Peso": {
            "Magro": [
                {
                    "nome": "Esteira (Corrida Moderada)",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Ciclo Ergômetro",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Saltos (Jumping Jacks)",
                    "musculosAlvo": ["Corpo Inteiro"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Burpees",
                    "musculosAlvo": ["Corpo Inteiro"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Natação",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Corrida",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Remo",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Jump Rope",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Mountain Climbers",
                    "musculosAlvo": ["Abdômen", "Cardiovascular"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Caminhada Rápida",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Padrão": [
                {
                    "nome": "Bicicleta Ergométrica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Elíptico",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Agachamento com Peso Corporal",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Flexão Inclinada",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Prancha",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Corrida",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Remo",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Jump Rope",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Mountain Climbers",
                    "musculosAlvo": ["Abdômen", "Cardiovascular"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Caminhada Rápida",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Acima do Peso": [
            ]
        }
    },
    "26-35": {
        "Ganho de massa muscular": {
            "Magro": [
                {
                    "nome": "Flexão de Braço",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Remada Curvada",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Agachamento Frontal",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Desenvolvimento Arnold",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Flexora",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Pull-Up com Peso Adicionado",
                    "musculosAlvo": ["Costas", "Braço"],
                    "repeticoes": "3 sets de 8-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Caminhada com Peso",
                    "musculosAlvo": ["Perna", "Abdômen"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Rosca Martelo",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
            "Padrão": [
                {
                    "nome": "Bicicleta Ergométrica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Elíptico",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Agachamento com Peso Corporal",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Flexão Inclinada",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Prancha",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Corrida",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Remo",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Jump Rope",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Mountain Climbers",
                    "musculosAlvo": ["Abdômen", "Cardiovascular"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Caminhada Rápida",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Acima do Peso": [
                {
                    "nome": "Flexão de Braço Inclinada",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Pulldown",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Braço Testa",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Desenvolvimento Arnold",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Flexora",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Pull-Up com Peso Adicionado",
                    "musculosAlvo": ["Costas", "Braço"],
                    "repeticoes": "3 sets de 8-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Caminhada com Peso",
                    "musculosAlvo": ["Perna", "Abdômen"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Rosca Martelo",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
        },
        "Perder Peso": {
            "Magro": [
                {
                    "nome": "Corrida de Resistência",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino HIIT (High-Intensity Interval Training)",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "Descanso de 30-60 segundos entre intervalos",
                },
                {
                    "nome": "Ciclismo",
                    "musculosAlvo": ["Pernas", "Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino Funcional",
                    "musculosAlvo": ["Corpo Inteiro"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Zumba",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Padrão": [
                {
                    "nome": "Natação",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Yoga",
                    "musculosAlvo": ["Flexibilidade", "Equilíbrio"],
                    "repeticoes": "60 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Caminhada Intensa",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino de Circuito",
                    "musculosAlvo": ["Cardiovascular", "Força"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Aeróbica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Acima do Peso": [
                {
                    "nome": "Caminhada Moderada",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino de Baixa Intensidade",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Aulas de Dança",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Hidroginástica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Pilates",
                    "musculosAlvo": ["Core", "Flexibilidade"],
                    "repeticoes": "60 minutos",
                    "intervalo": "N/A",
                },
            ],
        },
    },
    "36-45": {
        "Ganho de massa muscular": {
            "Magro": [
                {
                    "nome": "Supino Inclinado",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Barra Fixa Pronada",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Agachamento Livre",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Desenvolvimento com Barra",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Extensora",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Elevação Lateral",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Puxada Frontal",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Stiff",
                    "musculosAlvo": ["Pernas", "Glúteos", "Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Abdominais Pernas Elevadas",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 15-20",
                    "intervalo": "Descanso de 60 segundos",
                },
            ],
            "Padrão": [
                {
                    "nome": "Flexão de Braço",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Remada Curvada",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Afundo",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Braço Corda",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Rosca Direta",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Flexora",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Prancha",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Agachamento Frontal",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
            "Acima do Peso": [
                {
                    "nome": "Flexão de Braço Inclinada",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Pulldown",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Agachamento com Barra",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Braço Testa",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Desenvolvimento Arnold",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Flexora",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Prancha Lateral",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 1 minuto cada lado",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Step",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 15-20",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
        },
        "Perder Peso": {
            "Magro": [
                {
                    "nome": "Corrida de Resistência",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino HIIT (High-Intensity Interval Training)",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "Descanso de 30-60 segundos entre intervalos",
                },
                {
                    "nome": "Ciclismo",
                    "musculosAlvo": ["Pernas", "Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino Funcional",
                    "musculosAlvo": ["Corpo Inteiro"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Zumba",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Padrão": [
                {
                    "nome": "Natação",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Yoga",
                    "musculosAlvo": ["Flexibilidade", "Equilíbrio"],
                    "repeticoes": "60 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Caminhada Intensa",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino de Circuito",
                    "musculosAlvo": ["Cardiovascular", "Força"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Aeróbica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Acima do Peso": [
                {
                    "nome": "Caminhada Moderada",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino de Baixa Intensidade",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Aulas de Dança",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Hidroginástica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Pilates",
                    "musculosAlvo": ["Core", "Flexibilidade"],
                    "repeticoes": "60 minutos",
                    "intervalo": "N/A",
                },
            ],
        },
    },
    "46+": {
        "Ganho de massa muscular": {
            "Magro": [
                {
                    "nome": "Supino Inclinado",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Barra Fixa Pronada",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Agachamento Livre",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Desenvolvimento com Barra",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Extensora",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Elevação Lateral",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Puxada Frontal",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Stiff",
                    "musculosAlvo": ["Pernas", "Glúteos", "Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Abdominais Pernas Elevadas",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 15-20",
                    "intervalo": "Descanso de 60 segundos",
                },
            ],
            "Padrão": [
                {
                    "nome": "Flexão de Braço",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Remada Curvada",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Afundo",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Braço Corda",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Rosca Direta",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Flexora",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Prancha",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 1 minuto",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Agachamento Frontal",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
            "Acima do Peso": [
                {
                    "nome": "Flexão de Braço Inclinada",
                    "musculosAlvo": ["Peitoral"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Pulldown",
                    "musculosAlvo": ["Costas"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Agachamento com Barra",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Braço Testa",
                    "musculosAlvo": ["Braço"],
                    "repeticoes": "3 sets de 10-15",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Desenvolvimento Arnold",
                    "musculosAlvo": ["Ombros"],
                    "repeticoes": "3 sets de 10-12",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Cadeira Flexora",
                    "musculosAlvo": ["Pernas"],
                    "repeticoes": "3 sets de 12-15",
                    "intervalo": "Descanso de 60-75 segundos",
                },
                {
                    "nome": "Prancha Lateral",
                    "musculosAlvo": ["Abdômen"],
                    "repeticoes": "3 sets de 1 minuto cada lado",
                    "intervalo": "Descanso de 30 segundos",
                },
                {
                    "nome": "Step",
                    "musculosAlvo": ["Pernas", "Glúteos"],
                    "repeticoes": "3 sets de 15-20",
                    "intervalo": "Descanso de 60-75 segundos",
                },
            ],
        },
        "Perder Peso": {
            "Magro": [
                {
                    "nome": "Corrida de Resistência",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino HIIT (High-Intensity Interval Training)",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "Descanso de 30-60 segundos entre intervalos",
                },
                {
                    "nome": "Ciclismo",
                    "musculosAlvo": ["Pernas", "Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino Funcional",
                    "musculosAlvo": ["Corpo Inteiro"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Zumba",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Padrão": [
                {
                    "nome": "Natação",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Yoga",
                    "musculosAlvo": ["Flexibilidade", "Equilíbrio"],
                    "repeticoes": "60 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Caminhada Intensa",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino de Circuito",
                    "musculosAlvo": ["Cardiovascular", "Força"],
                    "repeticoes": "3 sets de 15-20 minutos",
                    "intervalo": "Descanso de 60 segundos",
                },
                {
                    "nome": "Aeróbica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
            ],
            "Acima do Peso": [
                {
                    "nome": "Caminhada Moderada",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Treino de Baixa Intensidade",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "20-30 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Aulas de Dança",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Hidroginástica",
                    "musculosAlvo": ["Cardiovascular"],
                    "repeticoes": "30-45 minutos",
                    "intervalo": "N/A",
                },
                {
                    "nome": "Pilates",
                    "musculosAlvo": ["Core", "Flexibilidade"],
                    "repeticoes": "60 minutos",
                    "intervalo": "N/A",
                },
            ],
        },
    }
}

export default Exercicios